services:

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma:
    build: ./prisma
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    command: >
       sh -c "npx prisma generate --schema=./prisma/schema.prisma &&
           npx prisma migrate deploy --schema=./prisma/schema.prisma &&
           npx prisma db seed --schema=./prisma/schema.prisma"

  mcp_server:
    build:
      context: ./mcp_server
    container_name: mcp_server
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/mydb
      MCP_PROTOCOL: "HTTP"
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
